Affinity Affairs/Pages/Admin/Create.cshtml.cs
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.Events;

namespace Affinity_Affairs.Pages.Admin
{
    public class CreateModel : PageModel
    {
        private readonly IEventsService _eventsService;
        public CreateModel(IEventsService eventsService)
        {
            _eventsService = eventsService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public EventInsertModel InsertModel { get; set; } = default!;
        [BindProperty]
        public IFormFile Image { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var fileBytes = await GetFileBytesAsync(Image);
                    await _eventsService.Post(InsertModel, fileBytes);
                    return RedirectToPage("/Events");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error creating event: " + ex.Message);
                }
            }
            return Page();
        }
        private async Task<byte[]> GetFileBytesAsync(IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                using (var stream = file.OpenReadStream())
                {
                    var memoryStream = new MemoryStream();
                    await stream.CopyToAsync(memoryStream);
                    return memoryStream.ToArray();
                }
            }
            return null;
        }
    }
}

Affinity Affairs/Pages/BookEvent.cshtml.cs
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.BookEvent;

namespace Affinity_Affairs.Pages
{
    public class BookEventPageModel : PageModel
    {
        private readonly IMiscService _miscService;
        [BindProperty]
        public BookEventModel BookEvent { get; set; }
        public BookEventPageModel(IMiscService miscService)
        {
            _miscService = miscService;
        }
        public void OnGet()
        {
            
        }
        public async Task<IActionResult> OnPost() 
        {
            await _miscService.BookEvent(BookEvent);
            return RedirectToPage();
        }


    }
}

Affinity Affairs/Pages/ContactUs.cshtml.cs
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.ContactUs;

namespace Affinity_Affairs.Pages
{
    public class ContactUsPageModel : PageModel
    {
        private readonly IMiscService _service;
        [BindProperty]
        public ContactUsModel ContactUs { get; set; }
        public ContactUsPageModel(IMiscService service)
        {
            _service = service;
        }
        public async Task<IActionResult> OnGet()
        {
            return Page();
        }
        public async Task<IActionResult> OnPost() 
        {
            await _service.ContactUs(ContactUs);
            return RedirectToPage();
        }
    }
}

Affinity Affairs/Pages/Create.cshtml.cs
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.Events;

namespace Affinity_Affairs.Pages
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public EventInsertModel InsertModel { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }

        private readonly IEventsService _eventsService;
        public CreateModel(IEventsService eventsService)
        {
            _eventsService = eventsService;
        }
        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var fileBytes = await GetFileBytesAsync(Image);
                    await _eventsService.Post(InsertModel, fileBytes);
                    return RedirectToPage("./events");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error creating event: " + ex.Message);
                }
            }
            return Page();
        }
        private async Task<byte[]> GetFileBytesAsync(IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                using (var stream = file.OpenReadStream())
                {
                    var memoryStream = new MemoryStream();
                    await stream.CopyToAsync(memoryStream);
                    return memoryStream.ToArray();
                }
            }
            return null;
        }
    }
}

Affinity Affairs/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Affinity_Affairs.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Affinity Affairs/Pages/EventDetail.cshtml.cs
using Affinity_Affairs.Data;
using Affinity_Affairs.Services;
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.Events;
using Models.EventUser;
using System.Web;

namespace Affinity_Affairs.Pages
{
    public class EventDetailModel : PageModel
    {
        private readonly IEventsService _eventService;
        private readonly UserManager<ApplicationUser> _userManager;
        public IEnumerable<EventViewModel> Events { get; set; }
        public IEnumerable<EventUserModel> EventUsers { get; set; }
        public EventDetailModel(IEventsService eventsService, UserManager<ApplicationUser> userManager)
        {
            _eventService = eventsService;
            _userManager = userManager;
        }
        public async void OnGet(string? searchTerm)
        {
            var SearchTerm = HttpUtility.UrlEncode(searchTerm);
            Events = await _eventService.GetAllEvents(SearchTerm);
            EventUsers = await _eventService.GetAllAttendees();
        }
        public async Task<IActionResult> OnPostRegisterAsync(Guid Id)
        {
            var user = await _userManager.GetUserAsync(User);
            string userId = user.Id;
            await _eventService.RegisterForEvent(Id, userId);
            return RedirectToPage("/EventDetail");
        }
        public async Task<IActionResult> OnPostCancelAsync(Guid Id)
        {
            var user = await _userManager.GetUserAsync(User);
            string userId = user.Id;
            await _eventService.CancelEventReservation(Id, userId);
            return RedirectToPage("/EventDetail");
        }

    }
}

Affinity Affairs/Pages/Events.cshtml.cs
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.Events;

namespace Affinity_Affairs.Pages
{
    public class EventsPageModel : PageModel
    {
        private readonly IEventsService _eventService;
        public EventsPageModel(IEventsService eventsService)
        {
            _eventService = eventsService;
        }
        public IEnumerable<EventModel> Events { get; set; }
        public async void OnGetAsync()
        {
            Events = await _eventService.GetAllEvents();
        }
        public async Task<IActionResult> OnPostDeleteAsync(Guid Id)
        {
            await _eventService.Delete(Id);
            return RedirectToPage("/Events");
        }

    }
}

Affinity Affairs/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Affinity_Affairs.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            
        }
    }
}

Affinity Affairs/Pages/MyEvents.cshtml.cs
using Affinity_Affairs.Data;
using Affinity_Affairs.Services;
using Affinity_Affairs.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.Events;
using Models.EventUser;

namespace Affinity_Affairs.Pages
{
    [Authorize]
    public class MyEventsModel : PageModel
    {
        public IEnumerable<EventViewModel> Events { get; set; }
        public IEnumerable<EventUserModel> EventUsers { get; set; }
        private readonly IEventsService _eventsService;
        private readonly UserManager<ApplicationUser> _userManager;
        public MyEventsModel(IEventsService eventsService, UserManager<ApplicationUser> userManager)
        {
            _eventsService = eventsService; 
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGet()
        {
            var user = await _userManager.GetUserAsync(User);
            Events = await _eventsService.GetUserEvents(user.Id);
            EventUsers = await _eventsService.GetAllAttendees();
            return Page();
        }
        public async Task<IActionResult> OnPostCancelAsync(Guid Id)
        {
            var user = await _userManager.GetUserAsync(User);
            string userId = user.Id;
            await _eventsService.CancelEventReservation(Id, userId);
            return RedirectToPage("/EventDetail");
        }

    }
}

Affinity Affairs/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Affinity_Affairs.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Affinity Affairs/Pages/BookEvent.cshtml
@page "/BookEvent"
@using Models.Enumeration
@model Affinity_Affairs.Pages.BookEventPageModel
@{
    ViewData["Title"] = "Book an Event";
}

<div id="book-now-container">
    <h2>Book Your Event Now</h2>
    <p>Fill in the form below to book your spot for the selected event.</p>

    <div id="book-now-form">
        <form method="post">
            <label for="event">Select Event:</label>
            <select asp-for="BookEvent.Category" class="form-control">
                @foreach (var category in (EventCategory[])Enum.GetValues(typeof(EventCategory)))
                {
                    <option value="@category">@category</option>
                }
            </select>

            <label asp-for="BookEvent.Name">Your Name:</label>
            <input type="text" id="name" asp-for="BookEvent.Name" required>

            <label asp-for="BookEvent.Email">Your Email:</label>
            <input type="email" id="email" asp-for="BookEvent.Email"required>

            <label asp-for="BookEvent.Phone">Your Phone:</label>
            <input type="tel" id="phone" asp-for="BookEvent.Phone"required>

            <label asp-for="BookEvent.Message">Additional Message:</label>
            <textarea id="message" asp-for="BookEvent.Message" rows="4"></textarea>

            <button type="submit">Book Now</button>
        </form>
    </div>
</div>

Affinity Affairs/Pages/ContactUs.cshtml
@page "/ContactUs"
@using Affinity_Affairs.Data
@using Microsoft.AspNetCore.Identity
@model Affinity_Affairs.Pages.ContactUsPageModel
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["Title"] = "Contact Us";
}


<div id="contact-container">
    <h2>Get in Touch</h2>
    <p>If you have any questions or inquiries, feel free to contact us using the form below.</p>

    @{
        if(SignInManager.IsSignedIn(User))
        {
            var user = UserManager.GetUserAsync(User).Result;
            <div id="contact-form">
                <form method="post">
                    <label asp-for="ContactUs.Name">Your Name:</label>
                    <input asp-for="ContactUs.Name" type="text" id="name" autocomplete="@user.FirstName+@user.LastName">

                    <label asp-for="ContactUs.Email">Your Email:</label>
                    <input type="email" id="email" asp-for="ContactUs.Email" autocomplete="@user.Email">

                    <label asp-for="ContactUs.Message">Your Message:</label>
                    <textarea id="message" asp-for="ContactUs.Message" rows="4" required></textarea>

                    <button type="submit">Send Message</button>
                </form>
            </div>
        }
        else
        {
            <div id="contact-form">
                <form method="post">
                    <label asp-for="ContactUs.Name">Your Name:</label>
                    <input asp-for="ContactUs.Name" type="text" id="name" required>

                    <label asp-for="ContactUs.Email">Your Email:</label>
                    <input type="email" id="email" asp-for="ContactUs.Email" required>

                    <label asp-for="ContactUs.Message">Your Message:</label>
                    <textarea id="message" asp-for="ContactUs.Message" rows="4" required></textarea>

                    <button type="submit">Send Message</button>
                </form>
            </div>
        }
    }

    
</div>

Affinity Affairs/Pages/Create.cshtml
@page "/Events/Create"
@model CreateModel;
@{
    ViewData["Title"] = "Create Event";
}

<h1>Create Event</h1>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="InsertModel.Name">Name:</label>
        <input asp-for="InsertModel.Name" class="form-control" />
        <span asp-validation-for="InsertModel.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="InsertModel.Location">Location:</label>
        <input asp-for="InsertModel.Location" class="form-control" />
        <span asp-validation-for="InsertModel.Location" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="InsertModel.Date">Date:</label>
        <input type="date" asp-for="InsertModel.Date" class="form-control" />
        <span asp-validation-for="InsertModel.Date" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="InsertModel.Description">Description:</label>
        <input asp-for="InsertModel.Description" class="form-control" />
        <span asp-validation-for="InsertModel.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Upload">Image (Optional):</label>
        <input type="file" id="Upload" asp-for="Image" class="form-control" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

Affinity Affairs/Pages/EventDetail.cshtml
@page "/EventDetail"
@using Affinity_Affairs.Data
@using Microsoft.AspNetCore.Identity
@model Affinity_Affairs.Pages.EventDetailModel
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["Title"] = "Event Details";
}

<div id="eventDetailMain">
    <h1>Explore All Events</h1>
    <p style="color:white">Explore and discover exciting events happening near you.</p>
</div>

@{
    bool HasUserRegistered(string userId, Guid eventId)
    {
        var result = Model.EventUsers.FirstOrDefault(x => x.EventId == eventId && x.UserId == userId);
        if (result != null)
        {
            return true;
        }
        return false;
    }
    var user = await UserManager.GetUserAsync(User);
    string userId = string.Empty;
    if (user != null)
    {
        userId = user.Id;
    }
}

<div id="event-details-container">

    @foreach(var item in Model.Events)
    {
        <h2>@item.Name</h2>
        <h4>@item.Date.ToLongDateString()</h4>
        <img class="my-4" src="data:image/png;base64,@Convert.ToBase64String(item.Image.Data)" alt="Image">
        @if(SignInManager.IsSignedIn(User))
        {
            if (HasUserRegistered(userId, item.Id))
            {
                <div class="btn-group my-2  btn-group-sm">
                    <button class="btn btn-secondary">Registered</button>
                    <form asp-page-handler="Cancel" asp-route-id="@item.Id" method="post">
                        <button type="submit" class="btn btn-danger mx-2">Cancel</button>
                    </form>
                </div>
            }
            else
            {
                <form asp-page-handler="Register" asp-route-id="@item.Id" method="post">
                    <button type="submit" class="btn btn-success btn-sm">Register</button>
                </form>
            }
        }
        <p class="my-3">@item.Description</p>
        <p class="my-3">Total Attendees : @item.TotalAttendees </p>
        <hr/>
    }

</div>

Affinity Affairs/Pages/Events.cshtml
@page "/Events"

@model EventsPageModel;

@{
    ViewData["Title"] = "Events";
}
<div id="hero">
    <h1>All Events</h1>
    <p>Explore and discover exciting events happening near you.</p>
</div>

<div id="events-container">
    @if (Model.Events != null)
    {
        @foreach (var item in Model.Events)
        {
            <a asp-page="/EventDetail" class="event">
                <img src="data:image/png;base64,@Convert.ToBase64String(item.Image.Data)" alt="Event 1 Image">
                <h5>@item.Name</h5>
                <p>Location: @item.Location</p>
                <p class="event-date">Date: @item.Date.ToString("dd:MM:yyyy")</p>
                @{
                    if(User.IsInRole("Admin"))
                    {
                        <form asp-page-handler="Delete" asp-route-id="@item.Id" method="post">
                            <button type="submit" class="btn btn-sm btn-danger">
                                Delete
                            </button>
                        </form>
                    }
                }
            </a>
        }
    }
    else
    {
        <p>There are no events to display.</p>
    }
</div>

Affinity Affairs/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Affinity Affairs";
}
<div id="hero">
    <h1>Welcome to Affinity Affairs</h1>
    <p style="color:white;">Explore and discover exciting events happening near you.</p>
</div>

<div id="content">
    <section id="home">
        <div class="d-flex justify-content-center">
            <div class="col-md-6">
                <form method="get" asp-page="/EventDetail">
                    <div class="input-group rounded-3">
                        <input type="text" class="form-control" id="searchTerm" placeholder="Search Events" name="searchTerm">
                        <button type="submit" class="btn btn-outline-success">Search</button>
                    </div>
                </form>
            </div>
        </div>

        <h2>Chrimas Eve Events!</h2>
        <img src="~/img/e4.jpeg" alt="Event 3 Image">
        <H2>Featured Events</H2>
        <div id="featured-events">
            <div class="event">
                <h2>Royal Ascot</h2>
                <p>Details about Event 1.</p>
                <img src="~/img/e1.jpg" alt="Event 1 Image">
            </div>

            <div class="event">
                <h2>Edinburgh Festival Fringe</h2>
                <p>Details about Event 2.</p>
                <img src="~/img/e2.jpg" alt="Event 2 Image">
            </div>

            <div class="event">
                <h2>Notting Hill Carnival</h2>
                <p>Details about Event 3.</p>
                <img src="~/img/e3.jpg" alt="Event 3 Image">
            </div>
        </div>

        <h2>Our Team</h2>
        <div id="team-members">
            <div class="team-member">
                <img src="~/img/man.jpg" alt="Team Member 1">
                <h3>John Doe</h3>
                <p>Position: Founder</p>
            </div>

            <div class="team-member">
                <img src="~/img/man2.jpg" alt="Team Member 2">
                <h3>Jane Smith</h3>
                <p>Position: Marketing Manager</p>
            </div>

            <div class="team-member">
                <img src="~/img/man3.jpg" alt="Team Member 3">
                <h3>Mark Johnson</h3>
                <p>Position: Event Coordinator</p>
            </div>
        </div>
       
    </section>
</div>

Affinity Affairs/Pages/MyEvents.cshtml
@page "/MyEvents"
@using Affinity_Affairs.Data
@using Microsoft.AspNetCore.Identity
@model Affinity_Affairs.Pages.MyEventsModel
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Attending Events";
}

<div class="container my-3">
    <button class="btn btn-outline-secondary">Download Data</button>
</div>

@{
    bool HasUserRegistered(string userId, Guid eventId)
    {
        var result = Model.EventUsers.FirstOrDefault(x => x.EventId == eventId && x.UserId == userId);
        if (result != null)
        {
            return true;
        }
        return false;
    }
}

<div id="events-container">
    @if (Model.Events != null)
    {
        var userId = (await UserManager.GetUserAsync(User)).Id;
        @foreach (var item in Model.Events)
        {
            <a asp-page="/MyEvents" class="event">
                <img src="data:image/png;base64,@Convert.ToBase64String(item.Image.Data)" alt="Event 1 Image">
                <h5>@item.Name</h5>
                <p>Location: @item.Location</p>
                <p class="event-date">Date: @item.Date.ToString("dd:MM:yyyy")</p>
                @{
                    if(HasUserRegistered(userId, item.Id))
                    {
                        <div class="btn-group my-2  btn-group-sm">
                            <button class="btn btn-secondary">Registered</button>
                            <form asp-page-handler="Cancel" asp-route-id="@item.Id" method="post">
                                <button type="submit" class="btn btn-danger mx-2">Cancel</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <form asp-page-handler="Register" asp-route-id="@item.Id" method="post">
                            <button type="submit" class="btn btn-success btn-sm">Register</button>
                        </form>
                    }

                }
                <form asp-page-handler="DownloadTicket" asp-route-id="@item.Id" method="post">
                    <button type="submit" class="btn btn-outline-secondary btn-sm">Download Ticket</button>
                </form>
            </a>
        }
    }
    else
    {
        <p>There are no events to display.</p>
    }
</div>